name: Create presentation pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install prerequisites
        run: |
          sudo apt update
          sudo apt install pandoc
          npm install reveal.js

      - name: Generate presentations
        run: |
          make clean
          make

      - name: Commit presentations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated presentation html files
          file_pattern: docs/*.html
